[greeter]
background = /boot/grub/themes/astronaut/background.png
theme-name = Astronaut-Grub
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb
icon-theme-name = Papirus-Dark
font-name = JetBrains Mono SemiBold 12
xft-dpi = 96
indicators = ~host;~spacer;~clock;~spacer;~power
clock-format = %a, %d %b  %H:%M
default-user-image = /etc/lightdm/im/images.png
user-background = false

